name: Deploy

on:
  workflow_dispatch:
    inputs:
      arch:
        description: Build arch
        required: true
        default: x64
        type: choice
        options:
        - x64
        - x86
        - arm64
        - arm
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Wait for Test
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: test
          token: ${{ github.token }}
      - name: Run Script
        run: python ${{ github.event.repository.name }} ${{ github.event.inputs.arch }} -portable -artifact 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: winget_${{ env.version }}_${{ github.event.inputs.arch }}
          path: |
            winget.exe
            WindowsPackageManager.dll
            resources.pri
      - name: Delete old worflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ${{ github.workflow }}
          retain_days: 0
          keep_minimum_runs: 0
