name: Deploy

on:
  workflow_dispatch:
    inputs:
      arch:
        description: Build arch
        required: true
        default: x64
        type: choice
        options:
        - x64
        - x86
        - arm64
        - arm
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      version: ""
    steps:
      - uses: actions/checkout@latest
      
      - name: Set up Python
        uses: actions/setup-python@latest
        with:
          python-version: 3.x
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Script
        run: python WingetInstaller.py ${{ github.event.inputs.arch }} -portable -artifact 
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@latest
        with:
          name: winget_${{ env.version }}_${{ github.event.inputs.arch }}
          path: |
            winget.exe
            WindowsPackageManager.dll
            resources.pri
        
      - name: Delete Old Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ${{ github.workflow }}
          retain_days: 0
          keep_minimum_runs: 0
