name: PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: "./"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WingetInstaller
        path: dist/windows

    - name: Delete Old Workflow Runs
      uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
      with:
        GITHUB_TOKEN: ${{ github.token }}
        repository: ${{ github.repository }}
        workflow: .github/workflows/PyInstaller.yml
        older-than-seconds: 0
