name: PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: "./"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WingetInstaller
        path: dist/windows
